/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pawelklapuch_sampleusingnativecinandroid_CLibraryWrapper */

#ifndef _Included_com_example_pawelklapuch_sampleusingnativecinandroid_CLibraryWrapper
#define _Included_com_example_pawelklapuch_sampleusingnativecinandroid_CLibraryWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pawelklapuch_sampleusingnativecinandroid_CLibraryWrapper
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pawelklapuch_sampleusingnativecinandroid_CLibraryWrapper_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
